version: "3"

services:
  node:
    # コンテナ名
    container_name: remix_v4
    image: node:16-alpine3.15
    build:
      dockerfile: Dockerfile
    # コンテナの中に入る
    tty: true
    # ボリューム
    volumes:
      - .:/workspace
      - /workspace/node_modules
      - /workspace/.cache
      - /workspace/build
      - /workspace/public/build
    # 環境変数
    environment:
      TZ: "Asia/Tokyo"
    command: sleep infinity
